"""empty message

Revision ID: 00b8b91bb980
Revises: 9c52539b9cfc
Create Date: 2020-10-18 22:02:46.578798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b8b91bb980'
down_revision = '9c52539b9cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Poem', sa.Column('used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Poem', 'used')
    # ### end Alembic commands ###
